version: '3.4'

services:
  app:
    hostname: app
    ports:
      - 8000:8000
    depends_on:
      - queue

  queue:
    hostname: queue
    image: rabbitmq:3-management

  worker:
    hostname: worker
    entrypoint: celery
    command: ["-A", "app.worker", "worker", "-l", "info", "-n", "%h", "--events", "-B"]
    depends_on:
      - queue

  flower:
    hostname: flower
    image: mher/flower
    command: ["celery", "flower"]
    environment:
      CELERY_BROKER_URL: amqp://guest@queue//
    ports:
      - 5555:5555
    depends_on:
      - queue
