version: '3.4'

services:
  app:
    image: houses:dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: dev
    command:
      [
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
    volumes:
      - ../:/app

  worker:
    image: houses:dev
    volumes:
      - ../:/app
